In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
df = pd.read_csv('dataset.csv')

In [ ]:
df.fillna({
    'Teacher_Quality': df['Teacher_Quality'].mode()[0],
    'Parental_Education_Level': df['Parental_Education_Level'].mode()[0],
    'Distance_from_Home': df['Distance_from_Home'].mode()[0]
},inplace=True)

In [ ]:
df.isna().sum()[df.isna().sum()>=1]

Series([], dtype: int64)

In [ ]:
# Calculate the first quartile (Q1) and third quartile (Q3) of the dataset.
q1 = df['Exam_Score'].quantile(0.25)
q3 = df['Exam_Score'].quantile(0.75)
# Compute the interquartile range (IQR) as the difference between Q3 and Q1 (IQR = Q3 – Q1).
IQR = q3 - q1
# Define the lower outlier threshold as Q1 – (1.5 * IQR) and the upper outlier threshold as Q3 + (1.5 * IQR).
lower_threshold = q1 - (1.5 * IQR)
upper_threshold = q3 + (1.5 * IQR)
# Identify any data points that fall below the lower threshold or above the upper threshold. These observations are considered outliers.
outliers = df[(df['Exam_Score'] < lower_threshold) | (df['Exam_Score'] > upper_threshold)]
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Sleep_Hours,Previous_Scores,Motivation_Level,Tutoring_Sessions,Family_Income,Teacher_Quality,Peer_Influence,Physical_Activity,Parental_Education_Level,Distance_from_Home,Exam_Score,Gender_Male,School_Type_Public,Extracurricular_Activities_Yes,Internet_Access_Yes,Learning_Disabilities_Yes
0,23,84,0.0,2.0,7,73,0.0,0,0.0,1.0,2.0,3,0.0,0.0,67,1,1,0,1,0
1,19,64,0.0,1.0,8,59,0.0,2,1.0,1.0,0.0,4,1.0,1.0,61,0,1,0,1,0
2,24,98,1.0,1.0,7,91,1.0,2,1.0,1.0,1.0,4,2.0,0.0,74,1,1,1,1,0
3,29,89,0.0,1.0,8,98,1.0,1,1.0,1.0,0.0,4,0.0,1.0,71,1,1,1,1,0
4,19,92,1.0,1.0,6,65,1.0,3,1.0,2.0,1.0,4,1.0,0.0,70,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,2.0,1.0,7,76,1.0,1,2.0,1.0,2.0,2,0.0,0.0,68,0,1,0,1,0
6603,23,76,2.0,1.0,8,81,1.0,3,0.0,2.0,2.0,2,0.0,0.0,69,0,1,0,1,0
6604,20,90,1.0,0.0,6,65,0.0,3,0.0,1.0,0.0,2,2.0,0.0,68,0,1,1,1,0
6605,10,86,2.0,2.0,6,91,2.0,2,0.0,1.0,2.0,3,0.0,2.0,68,0,0,1,1,0
6606,15,67,1.0,0.0,9,94,1.0,0,1.0,1.0,2.0,4,2.0,0.0,64,1,1,1,1,0

In [ ]:
df_Gender = pd.get_dummies(df['Gender'],dtype=int,drop_first=True,prefix='Gender')
df_School_Type = pd.get_dummies(df['School_Type'],dtype=int,drop_first=True,prefix='School_Type')
df_Extracurricular_Activities = pd.get_dummies(df['Extracurricular_Activities'],dtype=int,drop_first=True,prefix='Extracurricular_Activities')
df_Internet_Access = pd.get_dummies(df['Internet_Access'],dtype=int,drop_first=True,prefix='Internet_Access')
df_Learning_Disabilities = pd.get_dummies(df['Learning_Disabilities'],dtype=int,drop_first=True,prefix='Learning_Disabilities')
df = pd.concat([df,df_Gender,df_School_Type,df_Extracurricular_Activities,df_Internet_Access,df_Learning_Disabilities],axis=1)
df.drop(columns=['Gender','School_Type','Extracurricular_Activities','Internet_Access','Learning_Disabilities'],inplace=True)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
categories = [
    ['Low','Medium','High'],
    ['Low','Medium','High'],
    ['Low','Medium','High'],
    ['Low','Medium','High'],
    ['Low','Medium','High'],
    ['Negative','Neutral','Positive'],
    ['Near','Moderate','Far'],
    ['High School', 'College', 'Postgraduate']
]
columns = [
    'Motivation_Level',
    'Access_to_Resources',
    'Teacher_Quality',
    'Family_Income',
    'Parental_Involvement',
    'Peer_Influence',
    'Distance_from_Home',
    'Parental_Education_Level'
]

encoder = OrdinalEncoder(categories=categories)
df[columns] = encoder.fit_transform(df[columns])

In [ ]:
cols_to_scale = ['Hours_Studied','Attendance','Previous_Scores']
df[cols_to_scale] = StandardScaler().fit_transform(df[cols_to_scale])

In [ ]:
# df.to_csv('cleaned_dataset.csv', index=False)
df.to_csv('cleaned_dataset.csv', index=False)